### ISSUE TITLE
Maximum call stack exceeded

### ISSUE THREAD

**Issue by sploders101** [nitroxplunge/bluealliance#2]
Hi, I am getting an error from your module stating that the maximum call stack has been exceeded. This is easily reproduced with any one of your commands using the module off of npm. However, it is easily fixed as well. Upon further inspection, the callTBA(request) function is calling itself on every request. An easy fix for this, would be one as follows.
```javascript
async callTBA(request) {
        var authkey = this.authkey;

        if(request!="/status") this.status = await this.callTBA("/status");// <--added an if statement to avoid the infinite loop
        return new Promise(function(resolve, reject) {
            var xhr = new XMLHttpRequest();

            xhr.onreadystatechange = function() { if (this.readyState === 4) resolve(JSON.parse(this.responseText)) }

            xhr.open("GET", "https://www.thebluealliance.com/api/v3" + request);
            xhr.setRequestHeader("X-TBA-Auth-Key", authkey);
            xhr.send();
        });
    }
```
As I am making my pit dashboard open source for any team to use, it would be nice if you could fix it in npm so that I don't have to rewrite your code in my script to circumvent the issue.

Thanks!
--
Shaun Keys

**Comment by nitroxplunge** [comment]
Hi Shaun! Thanks for noticing this, it will be fixed in less than an hour.

Isaac, FRC 7308

**Comment by nitroxplunge** [comment]
The bug is now fixed and both the GitHub repository and NPM package has been updated.
